# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0001_New start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
